[package]
name = "acpos"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
postgres = "0.19.8"
serde = "1.0.148"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.26.0", features = ["full"] }
